### ISSUE TITLE
TSL handshake problem

### ISSUE THREAD

**Issue by umbros** [italia/spid-testenv-identityserver#1]
_From @umbros on October 2, 2017 22:19_

_From @umbros on September 22, 2017 8:53_

TLS handshake problem for localhost idp/sp

_Copied from original issue: italia/spid-testenv#7_

_Copied from original issue: italia/spid-testenv-identityserver-old#5_

**Comment by umbros** [comment]
_From @alexrj on September 24, 2017 19:40_

@umbros, forse il mio commit risolve il problema anche per te?
Io l'avevo notato perché con Safari non riuscivo ad aprire la console di WSO2.

**Comment by umbros** [comment]
E' necessario utilizzare la mutua autenticazione tra idp e sp e viceversa. In lavorazione

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#9
