### ISSUE TITLE
Dove posso trovare i log delle richieste di autenticazione (SAML2) non andate a buon fine?

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-identityserver#11]
Riapro qui una issue che avevo erroneamente aperto nel progetto [spid-testenv-docker](https://github.com/italia/spid-testenv-docker/issues/12)

#### Post iniziale:
Quando una richiesta di autenticazione viene rifiutata dal servizio IdP WSO2, mi viene mostrata una pagina web mi dice che l'autenticazione non ha funzionato e di guardare nei log per saperne di più:
SAML 2.0 based Single Sign-On
Not a valid SAML 2.0 Request Message!
The message was not recognized by the SAML 2.0 SSO Provider. Please check the logs for more details
Per controllare i log mi sono autenticato nel servizio WSO2 (nel mio caso https://localhost:9443, usando admin come utente e password, come riportato nel readme di questo progetto) e sono andato nel tab Monitor, dove ho trovato le sezioni "Application Logs" e "System Logs", ma non ho trovato il log che contenga la mia richiesta.
Dove devo andare per trovare tali log?

#### Risposta da @amusarra:
@ncarandini Ti conviene filtrare per ERROR. Gli errori più comuni sono che l'SP non è registrato correttamente, l'AuthnRequest fa riferimento ad un SP non registrato oppure c'è qualche errore nella signature. Comunque l'errore è riportato nella SAML Response.

#### Mia risposta:
@amusarra nel server WSO2 esistono molti log, quindi ok filtrare per ERROR (ottimo suggerimento, grazie) ma vorrei anche sapere, se possibile, in quale log specifico devo guardare.
Per quanto riguarda leggere l'errore dallo status della risposta, purtroppo non mi viene inoltrata alcuna risposta.
L'errore avviene prima di mostrare la maschera di login all'utente, in quanto è stata rifiutata la richiesta, quindi la risposta è ridirezionata non al mio endpoint ma ad una pagina del servizio IdP stesso, col messaggio di errore di cui sopra:
![image](https://user-images.githubusercontent.com/139274/33999967-4286cdbc-e0ec-11e7-9e2e-f7bb909fa029.png)
Quindi l'unica è "ravanare" nel log.
Che poi magari dipende tutto dal fatto che né il backend né il servizio IdP hanno certificati validi e che questo crea problemi, ma intanto vorrei guardare che dice nel log.

#### Domanda rimasta aperta:
In quale log specifico vengono registrate le chiamate fallite?

**Comment by amusarra** [comment]
Invece di utilizzare l'istanza online dell'idp WSO2, ti consiglierei di tirare su l'idp localmente in modo che puoi facilmente analizzare i file di log. Ti consiglierei anche ti utilizzare i SAMLTools disponibili online per la verifica della validità delle tue richieste SAML. Immagino che tu abbia comunque generato il tuo certificato e messo anche su idp.

**Comment by ncarandini** [comment]
Io uso l'istanza dell'idp WSO2 che gira sul Docker container creato con il Docker Composer file di questo progetto, e si ho generato la mia chiave privata e mi sono registrato come SP nella suddetta istanza del servizio IdP. Considera che il medesimo servizio SP lo uso col servizio IdP di test di Poste Italiane e funziona perfettamente, quindi devo capire cosa sbaglio nel fare le richieste verso WSO2 e per questo il log di WSO2 mi sarebbe oltremodo utile, rispetto ad un tool generico come SAMLTools, di cui comunque ti ringrazio per la segnalazione e che non mancherò di utilizzare.

**Comment by ncarandini** [comment]
Ho finalmente trovato il modo di loggare il processo di autorizzazione SAML:

Bisogna modificare la riga 84 del file
`/spid-testenvironment/is/identity-server/repository/conf/log4j.properties` 
togliendo il commento alla riga.

Una volta modificato il file di configurazione dei log, basta riavviare l'identity server dalla management console.

A questo punto, facendo una prova col SAML Request Validator:

![image](https://user-images.githubusercontent.com/139274/34099866-018de028-e3e1-11e7-95f2-b818478e9530.png)

Oltre all'errore del validatore:

![image](https://user-images.githubusercontent.com/139274/34099947-3e50104e-e3e1-11e7-9f08-6309971e1397.png)

Andando nei log di sistema si trovano finalmente i messaggi di errore:

![image](https://user-images.githubusercontent.com/139274/34100165-e6ee28c6-e3e1-11e7-89d8-a871ba6d7b51.png)

Ora tocca capire come risolvere gli errori, ma questa è un'altra issue.

**Comment by ruphy** [comment]
@umbros @alexrj che ne dite, avrebbe senso modificare la docker image dell'environment di test per integrare questa modifica?

**Comment by ncarandini** [comment]
Devo aggiungere un paio di cose, che ho appena sperimentato:
1. I messaggi di log che ho potuto ricavare sono quasi del tutto inutili, almeno nel mio caso. Ad esempio, provando ad inviare la richiesta dal mio SP, il log dell'errore è stato a dir poco criptico:
![image](https://user-images.githubusercontent.com/139274/34113087-e06a15f0-e40e-11e7-81a1-ffb990c94008.png)
visto che mi dice solo che c'è una query string nulla :-(

2. Il Request validator offre migliori indicazioni, sempre che lo si sappia usare, e forse è utile segnalare (visto che mi è capitato di fare proprio questo errore) che nel campo va inserito non tanto la richiesta XML in chiaro qyanto piuttosto la richiesta XML signed e convertita in base 64:
![image](https://user-images.githubusercontent.com/139274/34113193-305880e2-e40f-11e7-8b9f-b4379bd1242a.png)

Così facendo si ha un'idea molto più chiara (e nel mio caso specifico sembra un problema di un campo che nelle specifiche non è obbligatorio, e "puzza" di bug di WSO2).
Credo dunque che la strada giusta (a onor del vero suggerita da @amusarra) sia quella di utilizzare questo strumento piuttosto che impazzire dietro a log difficili da impostare e ancor più difficili da interpretare.

**Comment by ncarandini** [comment]
Altro aggiornamento, che mi lascia interdetto:
Ho provato ad aggiungere nella richiesta l'assertion consumer URL, anche se non necessaria secondo la documentazione SAMLp 2.0, perché in sua assenza l'IdP dovrebbe gestire comunque la richiesta, come ben specificato in questo [post](http://dulanja.blogspot.it/2014/07/dissecting-saml-spec-validation-of.html).
La cosa davvero strana è che se lo faccio:
![image](https://user-images.githubusercontent.com/139274/34156364-2f518636-e4bd-11e7-83ce-d22efe1aa31d.png)
e prendo la richiesta XML signed e convertita in base 64, e la inserisco nel Request Validator, si inchioda!
![image](https://user-images.githubusercontent.com/139274/34156433-8c01f898-e4bd-11e7-8bd8-575eaa5639e6.png)

Come al solito, i log dicono poco o niente di utile per me, anche se sono certamente utili per comunicarli al team di WSO2:
![image](https://user-images.githubusercontent.com/139274/34156561-0737ca06-e4be-11e7-97b1-37d368d2407b.png)

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#13
