### ISSUE TITLE
Ma c'è qualcuno che riesce ad usare questo servizio IdP di test con successo?

### ISSUE THREAD

**Issue by ncarandini** [italia/spid-testenv-identityserver#12]
Visto che ci sto perdendo davvero troppo tempo (rispetto a quanto preventivato) per far funzionare questo servizio di test, c'è qualcuno che può postare qui un file XML di una richiesta di Authn che una volta firmato e convertito in base64 funzioni col Request Validator?

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#14
