### ISSUE TITLE
Error on wso2server.sh 

### ISSUE THREAD

**Issue by umbros** [italia/spid-testenv-identityserver#5]
ERROR: for identityserver  Cannot start service identityserver: oci runtime error: container_linux.go:265: starting container process caused "exec: \"wso2server.sh\": executable file not found in $PATH"

**Comment by alexrj** [comment]
When does this happen? Under what deployment method and operating system?

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#12
